# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  test-race:
    cmds:
      - |
        go test -tags dynamic -v `go list ./...` \
          -coverprofile=coverage.txt -cover -failfast
      - go tool cover -func coverage.txt

  chglog:
    cmds:
      - git-chglog -o CHANGELOG.md
